micronaut:
  application:
    name: snippetsOfCode
  io:
    watch:
      enabled: true
      restart: true
      paths: src/main
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
  views:
    thymeleaf:
      enabled: true
      character-encoding: "UTF-8"
      suffix: ".html"
      cacheable: false


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/snippetscode
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
